name: Build Nightly

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  downloadURL: https://mcben.github.io/ingress-intel-total-conversion-R/nightly/total-conversion-build.user.js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: yarn install
      - run: yarn build
          
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: yarn test
      
  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          target-folder: nightly
