name: Build Nightly

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  downloadURL: https://mcben.github.io/ingress-intel-total-conversion-R/nightly/total-conversion-build.user.js

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: 'true'
      - name: install dependency
        run: yarn install
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@920cbb300dcd3f0568dbc42700c61e2fd9e6139c # v4.6.4
        with:
          folder: build
          target-folder: nightly
