name: Build Nightly

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  downloadURL: https://mcben.github.io/ingress-intel-total-conversion-R/nightly/total-conversion-build.user.js

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: 'true'
      - name: install dependency
        run: yarn install
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@15de0f09300eea763baee31dff6c6184995c5f6a # v4.7.2
        with:
          folder: build
          target-folder: nightly
