name: PR Review

on:
  pull_request:

jobs:
  codestyle:
    name: reviewdog (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          fail_on_error: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: yarn install  
      - run: yarn build  
