name: PR Review

on:
  pull_request:

jobs:
  codestyle:
    name: reviewdog (github-pr-review)
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          submodules: 'true'

      - run: yarn install
      - uses: reviewdog/action-eslint@9a6606695f1ef9709cce821919ca3b2a6d5e6bb5 # v1.32.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          fail_on_error: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          submodules: 'true'
      - run: yarn install  
      - run: yarn build  
